import React from 'react';

export const JewelleryItems = [
    {
        id:"anklet",
        name:"Anklet",
        ws:0,
        mc:0,
        min:0,
        max:0,
        isExchange: false,
        isGold:false,
        touch:65,
        tab:'Silver',
        perGram:0,
    },
    {
        id:"ldsBracelet",
        name:"Ladies Bracelet",
        ws:0,
        mc:0,
        min:0,
        max:0,
        isExchange: false,
        isGold:false,
        touch:65,
        tab:'Silver',
        perGram:0,
    },
    {
        id:"dollar",
        name:"Dollar",
        ws:0,
        mc:0,
        min:0,
        max:0,
        isExchange: false,
        isGold:false,
        touch:65,
        tab:'Silver',
        perGram:0,
    },
    {
        id:"Khada",
        name:"Khada",
        ws:0,
        mc:0,
        min:0,
        max:0,
        isExchange: false,
        isGold:false,
        touch:65,
        tab:'Silver',
        perGram:0,
    },
    {
        id:"lakshmiFaceRglr",
        name:"Lakshmi Face Regular",
        ws:0,
        mc:0,
        min:0,
        max:0,
        isExchange: false,
        isGold:false,
        touch:70,
        tab:'Silver',
        perGram:0,
    },
    {
        id:"lakshmiFaceHM",
        name:"Lakshmi Face HM",
        ws:0,
        mc:0,
        min:0,
        max:0,
        isExchange: false,
        isGold:false,
        touch:80,
        tab:'Silver',
        perGram:0,
    },
    {
        id:"diya",
        name:"Diya",
        ws:0,
        mc:0,
        min:0,
        max:0,
        isExchange: false,
        isGold:false,
        touch:80,
        tab:'Silver',
        perGram:0,
    },
    {
        id:"plate",
        name:"Plate",
        ws:0,
        mc:0,
        min:0,
        max:0,
        isExchange: false,
        isGold:false,
        touch:80,
        tab:'Silver',
        perGram:0,
    },
    {
        id:"hollowIdol",
        name:"Hollow Idol",
        ws:0,
        mc:0,
        min:0,
        max:0,
        isExchange: false,
        isGold:false,
        touch:80,
        tab:'Silver',
        perGram:0,
    },
    {
        id:"solidIdol",
        name:"Solid Idol",
        ws:0,
        mc:0,
        min:0,
        max:0,
        isExchange: false,
        isGold:false,
        touch:80,
        tab:'Silver',
        perGram:0,
    },
    {
        id:"chatri",
        name:"Chatri",
        ws:0,
        mc:0,
        min:0,
        max:0,
        isExchange: false,
        isGold:false,
        touch:80,
        tab:'Silver',
        perGram:0,
    },
    {
        id:"toeRing_waistChain",
        name:"Toe Ring/waist Chain",
        ws:0,
        mc:0,
        min:0,
        max:0,
        isExchange: false,
        isGold:false,
        touch:80,
        tab:'Silver',
        perGram:0,
    },
    {
        id:"gentsBracelet_neckChain",
        name:"Gents Bracelet/Neck Chain",
        ws:0,
        mc:0,
        min:0,
        max:0,
        isExchange: false,
        isGold:false,
        touch:65,
        tab:'Silver',
        perGram:0,
    },
    {
        id:"gentsRing",
        name:"Mens Ring",
        ws:0,
        mc:0,
        min:0,
        max:0,
        isExchange: false,
        isGold:false,
        touch:55,
        tab:'Silver',
        perGram:0,
    },
    {
        id:"LdsRing",
        name:"Ladies Ring",
        ws:0,
        mc:0,
        min:0,
        max:0,
        isExchange: false,
        isGold:false,
        touch:55,
        tab:'Silver',
        perGram:0,
    },      

    {
        name:"75 T",
        ws:0,
        mc:0,
        min:0,
        max:0,
        isExchange: false,
        isGold:true,
        touch:75,
        tab:'Gold',
        perGram:0,
    },
    {
        name:"85 KDM",
        ws:0,
        mc:0,
        min:0,
        max:0,
        isExchange: false,
        isGold:true,
        touch:85,
        tab:'Gold',
        perGram:0,
    },
    {
        name:"92 Hallmark",
        ws:0,
        mc:0,
        min:0,
        max:0,
        isExchange: false,
        isGold:true,
        touch:92,
        tab:'Gold',
        perGram:0,
    },
    {
        name:"Silver item",
        ws:0,
        mc:0,
        min:0,
        max:0,
        isExchange: true,
        isGold:false,
        touch:0,
        tab:'Exchange',
        perGram:0,
    },
    {
        name:"75 T",
        ws:0,
        mc:0,
        min:0,
        max:0,
        isExchange: true,
        isGold:false,
        touch:0,
        tab:'Exchange',
        perGram:0,
    },
    {
        name:"85 KDM",
        ws:0,
        mc:0,
        min:0,
        max:0,
        isExchange: true,
        isGold:false,
        touch:0,
        tab:'Exchange',
        perGram:0,
    },
    {
        name:"916 Item",
        ws:0,
        mc:0,
        min:0,
        max:0,
        isExchange: true,
        isGold:false,
        touch:0,
        tab:'Exchange',
        perGram:0,
    },

  ];

  export const GoldWastageChart = [
    {
        min: 0.000, max:0.500, ws: 0.100
    },
    {
        min: 0.501, max:0.700, ws: 0.120
    },
    {
        min: 0.701, max:0.800, ws: 0.130
    },
    {
        min: 0.801, max:1.000, ws: 0.150
    },
    {
        min: 1.001, max:1.250, ws: 0.200
    },
    {
        min: 1.251, max:1.500, ws: 0.250
    },
    {
        min: 1.501, max:1.750, ws: 0.300
    },
    {
        min: 1.751, max:2.000, ws: 0.350
    },
    {
        min: 2.001, max:2.250, ws: 0.400
    },
    {
        min: 2.251, max:2.500, ws: 0.450
    },
    {
        min: 2.501, max:2.750, ws: 0.500
    }
   

  ]